language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database lampcp;'
  - app/console doctrine:schema:update --force
  - app/console lampcp:config:init

script: phpunit -c app --exclude-group=database
