##########################################
#
# LampCP
# https://github.com/jeboehm/LampCP
#
# Licensed under the GPL Version 2 license
# http://www.gnu.org/licenses/gpl-2.0.txt
#
##########################################

imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml, ignore_errors = true }
    - { resource: security.yml }

framework:
    translator:          { fallback: "%locale%" }
    secret:              %crypt%
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:                true
    csrf_protection:     true
    validation:          { enable_annotations: true }
    templating:          { engines: ['twig'] }
    default_locale:      "%locale%"
    trust_proxy_headers: false
    session:             ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "JeboehmLampcpCoreBundle:Form:form_div_layout.html.twig"
    globals:
        env:          "%kernel.environment%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jeboehm\Lampcp\CoreBundle\Entity\Admin
    service:
        mailer: fos_user.mailer.noop

knp_menu:
   twig:
       template: "JeboehmLampcpCoreBundle:Base:menu.html.twig"

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
