##########################################
#
# LampCP
# https://github.com/jeboehm/LampCP
#
# Licensed under the GPL Version 2 license
# http://www.gnu.org/licenses/gpl-2.0.txt
#
##########################################

parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     lampcp
    database_user:     root
    database_password: ~

    locale:            de
    crypt:             LampCP-please-change-this
