##########################################
#
# LampCP
# https://github.com/jeboehm/LampCP
#
# Licensed under the GPL Version 2 license
# http://www.gnu.org/licenses/gpl-2.0.txt
#
##########################################

jeboehm_lampcp_core:
    resource: "@JeboehmLampcpCoreBundle/Controller/"
    type:     annotation
    prefix:   /

jeboehm_lampcp_zonegenerator:
    resource: "@JeboehmLampcpZoneGeneratorBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
