jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Jboehm\Lampcp\CoreBundle\Entity\Admin:
          algorithm:         sha1
          encode_as_base64:  false
          iterations:        1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: JboehmLampcpCoreBundle:Admin, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Control Panel Login"

    access_control:
        - { path: ^/, roles: ROLE_USER }