security:
    encoders:
        Jboehm\Lampcp\CoreBundle\Entity\Admin:
          algorithm:         sha1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        administrators:
            entity: { class: JboehmLampcpCoreBundle:Admin, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:    ^/login$
            anonymous:  ~

        lampcp:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path:            /

                username_parameter: _username
                password_parameter: _password

            logout:
                path:   /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
