##########################################
#
# LampCP
# https://github.com/jeboehm/LampCP
#
# Licensed under the GPL Version 2 license
# http://www.gnu.org/licenses/gpl-2.0.txt
#
##########################################

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER ROLE_DYNDNS
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dyndns:
            pattern: ^/nic
            anonymous: ~
            http_basic:
                realm: DynDNS Update

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/config/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/nic, role: ROLE_DYNDNS }
        - { path: ^/, role: ROLE_ADMIN }
