##
# LampCP
# https://github.com/jeboehm/LampCP
#
# Licensed under the GPL Version 2 license
# http://www.gnu.org/licenses/gpl-2.0.txt
#
##

##
#
# Fieldtypes:
#  [string], [password], [bool], [integer]
#
# Optionnames should be translated in
#  Resources/translations
#
##

config:
    mysql:
        root_user: [string]
        root_password: [password]

    paths:
        web_root_dir: [string]
        mail_root_dir: [string]
        unix_passwd_file: [string]
        unix_group_file: [string]

    apache:
        config_directory: [string]
